### ISSUE TITLE
Support Terminus v1.0

### ISSUE THREAD

**Issue by ccharlton** [uberhacker/tps#1]
Any changes needed to this plugin to support Terminus v1.0?

**Comment by uberhacker** [comment]
Hey @ccharlton: This functionality has been merged in with the [plugin manager PR](https://github.com/pantheon-systems/terminus/pull/1498) for 1.x.  The command `terminus plugin:find awesome-plugin` basically does a `composer search -t terminus-plugin awesome-plugin` in the background and lists all available plugins registered at packagist.org.
